language: csharp
solution: Rebilly.sln
before_install: # We need to download nuget.exe due to: https://github.com/travis-ci/travis-ci/issues/5932
  #- sudo apt-get install nunit-console
  - mkdir -p .nuget
  - wget -O .nuget/nuget.exe https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
  - mono .nuget/nuget.exe
install:
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
  - mono .nuget/nuget.exe restore Rebilly.sln -Verbosity detailed
script:
  - xbuild Rebilly.sln
after_script:
  #- nunit-console Tests/bin/Debug/Tests.dll
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe Tests/bin/Debug/Tests.dll