language: csharp
solution: Rebilly.sln
before_install:
  - sudo apt-get install nunit-console
  - mkdir -p .nuget
  - wget -O .nuget/nuget.exe https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
  - mono .nuget/nuget.exe
install:
  - mono .nuget/nuget.exe restore Rebilly.sln
script:
  - xbuild Rebilly.sln
after_script:
  - nunit-console Tests/bin/Release/Tests.dll